version: '3'

services:
  app:
    container_name: "flask-setup-app-dev"
    build:
      context: ./../..
      dockerfile: deploy/dev/Dockerfile
    command: flask run --reload
    volumes:
      - ../../src/project/:/usr/src/app/
      - deploy-folder-dev:/usr/src/app/deploy/
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: "flask-setup-db-dev"
    image: "postgres:13-alpine"
    volumes:
      - flask-setup-database-dev:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  flask-setup-database-dev: {}
  deploy-folder-dev: {}
