"""user_is_email_confirmed

Revision ID: 803246b2bf90
Revises: 39cdec6909c9
Create Date: 2023-10-11 13:00:33.334872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803246b2bf90'
down_revision = '39cdec6909c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_email_confirmed')

    # ### end Alembic commands ###
